-- Migration 0001_initial — TrafficVaultHub foundational identity & organization schema
-- Target: Cloudflare D1 (SQLite)
--
-- Scope (Phase 0): ONLY the tenancy/identity/RBAC foundation described in
-- PRD §7–§10 and §92. No business tables, no monetary fields, no seed data.
--
-- Conventions
--   * Primary keys are TEXT UUIDs generated by the application (D1 has no
--     native UUID type; TEXT ids avoid cross-tenant id enumeration).
--   * All timestamps are UTC ISO-8601 strings, e.g. 2026-09-22T08:00:00Z
--     (PRD §15). Defaults use strftime('%Y-%m-%dT%H:%M:%fZ','now').
--   * Soft deletion via status / deleted_at instead of physical DELETE (PRD §95).
--   * Applied migrations are immutable (PRD §109). Never edit this file after
--     it has been applied; add a new migration instead.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- organizations — every tenant (PRD §7, §8)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS organizations (
  id            TEXT PRIMARY KEY,
  type          TEXT NOT NULL
                CHECK (type IN ('PLATFORM','ADVERTISER','AFFILIATE','PARTNER','AGENCY')),
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE','RESTRICTED','SUSPENDED','TERMINATED')),
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  deleted_at    TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_organizations_slug ON organizations (slug);
CREATE INDEX IF NOT EXISTS ix_organizations_type_status ON organizations (type, status);

-- ---------------------------------------------------------------------------
-- users — global identities; tenant access is granted via organization_members
-- (PRD §12). Credential storage is delegated to the authentication provider
-- chosen in ADR-001; only the provider's opaque subject id is stored here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                  TEXT PRIMARY KEY,
  email               TEXT NOT NULL,
  email_verified_at   TEXT,
  display_name        TEXT,
  auth_provider       TEXT,
  auth_subject        TEXT,
  status              TEXT NOT NULL DEFAULT 'ACTIVE'
                      CHECK (status IN ('ACTIVE','RESTRICTED','SUSPENDED','TERMINATED')),
  timezone            TEXT NOT NULL DEFAULT 'UTC',
  locale              TEXT NOT NULL DEFAULT 'en',
  last_login_at       TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  deleted_at          TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_auth_provider_subject
  ON users (auth_provider, auth_subject)
  WHERE auth_provider IS NOT NULL AND auth_subject IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_users_status ON users (status);

-- ---------------------------------------------------------------------------
-- roles — RBAC roles (PRD §9). A role is either platform-wide
-- (organization_id NULL, is_system = 1) or scoped to one organization.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id                TEXT PRIMARY KEY,
  organization_id   TEXT REFERENCES organizations (id) ON DELETE CASCADE,
  key               TEXT NOT NULL,
  name              TEXT NOT NULL,
  description       TEXT,
  is_system         INTEGER NOT NULL DEFAULT 0 CHECK (is_system IN (0,1)),
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Role keys must be unique per tenant; system roles (NULL org) unique globally.
CREATE UNIQUE INDEX IF NOT EXISTS ux_roles_org_key
  ON roles (organization_id, key) WHERE organization_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_roles_system_key
  ON roles (key) WHERE organization_id IS NULL;
CREATE INDEX IF NOT EXISTS ix_roles_organization_id ON roles (organization_id);

-- ---------------------------------------------------------------------------
-- permissions — fine-grained action catalogue (PRD §10), e.g. offers.read
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS permissions (
  id            TEXT PRIMARY KEY,
  key           TEXT NOT NULL,
  resource      TEXT NOT NULL,
  action        TEXT NOT NULL,
  description   TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_permissions_key ON permissions (key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_permissions_resource_action ON permissions (resource, action);

-- ---------------------------------------------------------------------------
-- role_permissions — many-to-many role ↔ permission
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id         TEXT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  permission_id   TEXT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS ix_role_permissions_permission_id ON role_permissions (permission_id);

-- ---------------------------------------------------------------------------
-- organization_members — user ↔ organization membership with an assigned role
-- (PRD §7, §94). Every tenant-scoped authorization check joins through here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS organization_members (
  id                TEXT PRIMARY KEY,
  organization_id   TEXT NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  user_id           TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role_id           TEXT NOT NULL REFERENCES roles (id) ON DELETE RESTRICT,
  status            TEXT NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('INVITED','ACTIVE','SUSPENDED','REMOVED')),
  invited_by_user_id TEXT REFERENCES users (id) ON DELETE SET NULL,
  joined_at         TEXT,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  removed_at        TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_organization_members_org_user
  ON organization_members (organization_id, user_id);
CREATE INDEX IF NOT EXISTS ix_organization_members_user_id ON organization_members (user_id);
CREATE INDEX IF NOT EXISTS ix_organization_members_role_id ON organization_members (role_id);
CREATE INDEX IF NOT EXISTS ix_organization_members_org_status
  ON organization_members (organization_id, status);
