-- Migration 0002_identity — TrafficVaultHub authentication foundation
-- Target: Cloudflare D1 (SQLite)
--
-- Scope (Phase 1, Unit 1 — Auth foundation; PRD §12, §98, §116):
--   * user_credentials  — password hashes (one active credential per user)
--   * sessions          — server-side opaque sessions (D1; see ADR-001)
--   * auth_tokens       — single-use hashed tokens for email verification and
--                         password reset
--   * auth_events       — login monitoring / audit trail for identity events
--
-- Additive only. Migration 0001 is immutable and is NOT modified here.
-- Session/device management (Unit 2), organizations (Unit 3) and MFA wiring
-- extend this schema in later additive migrations if needed.
--
-- Conventions (same as 0001): TEXT UUID primary keys generated by the
-- application; UTC ISO-8601 TEXT timestamps; soft deletion where relevant.
-- Secret material (session ids, raw tokens) is NEVER stored — only SHA-256
-- digests, so a database read alone cannot be replayed as a credential.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- user_credentials — password credential for email/password authentication.
-- The hash string is self-describing ("$scrypt$..." with parameters + salt)
-- so parameters can be raised over time and rows re-hashed on next login.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_credentials (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  password_hash       TEXT NOT NULL,
  hash_algorithm      TEXT NOT NULL DEFAULT 'scrypt',
  password_changed_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  failed_attempts     INTEGER NOT NULL DEFAULT 0,
  locked_until        TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_user_credentials_user_id ON user_credentials (user_id);

-- ---------------------------------------------------------------------------
-- sessions — opaque bearer sessions. The client holds a random session
-- secret; the server stores only its SHA-256 digest (`token_hash`).
-- `expires_at` is absolute; `revoked_at` supports explicit revocation (Unit 2
-- will add listing/revocation endpoints on top of this table).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
  id                TEXT PRIMARY KEY,
  user_id           TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash        TEXT NOT NULL,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  last_seen_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  expires_at        TEXT NOT NULL,
  revoked_at        TEXT,
  revoked_reason    TEXT,
  ip_address        TEXT,
  user_agent        TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sessions_token_hash ON sessions (token_hash);
CREATE INDEX IF NOT EXISTS ix_sessions_user_id ON sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_expires_at ON sessions (expires_at);

-- ---------------------------------------------------------------------------
-- auth_tokens — single-use, time-limited tokens delivered out of band
-- (email). Raw token is never stored; `token_hash` = SHA-256(raw).
-- purpose: EMAIL_VERIFICATION | PASSWORD_RESET
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_tokens (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  purpose       TEXT NOT NULL
                CHECK (purpose IN ('EMAIL_VERIFICATION','PASSWORD_RESET')),
  token_hash    TEXT NOT NULL,
  expires_at    TEXT NOT NULL,
  consumed_at   TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_auth_tokens_token_hash ON auth_tokens (token_hash);
CREATE INDEX IF NOT EXISTS ix_auth_tokens_user_purpose ON auth_tokens (user_id, purpose);

-- ---------------------------------------------------------------------------
-- auth_events — login monitoring (PRD §12, §102). Never stores passwords or
-- token material. `user_id` is nullable so failed logins against unknown
-- emails can still be counted without leaking account existence.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_events (
  id            TEXT PRIMARY KEY,
  user_id       TEXT REFERENCES users (id) ON DELETE SET NULL,
  event_type    TEXT NOT NULL
                CHECK (event_type IN (
                  'SIGNUP','EMAIL_VERIFIED',
                  'LOGIN_SUCCEEDED','LOGIN_FAILED','LOGOUT',
                  'PASSWORD_RESET_REQUESTED','PASSWORD_RESET_COMPLETED'
                )),
  session_id    TEXT,
  ip_address    TEXT,
  user_agent    TEXT,
  request_id    TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS ix_auth_events_user_created ON auth_events (user_id, created_at);
CREATE INDEX IF NOT EXISTS ix_auth_events_type_created ON auth_events (event_type, created_at);

-- ---------------------------------------------------------------------------
-- MFA hook (PRD §12). Stored as a per-user flag only; enrolment/verification
-- is NOT implemented in Unit 1 — the backend exposes a clearly-marked stub
-- that reports MFA as not yet available and never fake-passes.
-- ---------------------------------------------------------------------------
ALTER TABLE users ADD COLUMN mfa_enabled INTEGER NOT NULL DEFAULT 0 CHECK (mfa_enabled IN (0,1));
